version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: "sls-sam-deployment-bucket"
    STACK_NAME: "your-sam-stack"
    TARGET_ROLE_ARN: "arn:aws:iam::TARGET_ACCOUNT_ID:role/CrossAccountPipelineRole"
    EXTERNAL_ID: "my-pipeline-external-id-abc123def"
    AWS_REGION: "ap-south-1"
    PARAM_OVERRIDES: ""

phases:
  install:
    runtime-versions:
      nodejs: 24
      python: 3.10
    commands:
      - echo "Installing Node.js 24 + build tools"
      - npm ci
      - python -m pip install --upgrade pip setuptools
      - pip install --upgrade aws-sam-cli
      - sam --version
      - npm --version
      - node --version

  pre_build:
    commands:
      - echo "Preparing cross-account environment"
      - |
        echo "Assuming target role $TARGET_ROLE_ARN with ExternalId $EXTERNAL_ID"
        CREDS=$(aws sts assume-role \
          --role-arn "$TARGET_ROLE_ARN" \
          --role-session-name "codebuild-${CODEBUILD_BUILD_NUMBER}" \
          --external-id "$EXTERNAL_ID" \
          --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
          --output text)
        export AWS_ACCESS_KEY_ID=$(echo $CREDS | cut -d' ' -f1)
        export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | cut -d' ' -f2)
        export AWS_SESSION_TOKEN=$(echo $CREDS | cut -d' ' -f3)
        export AWS_DEFAULT_REGION="$AWS_REGION"
        echo "Assumed role; using target account credentials"
      - aws sts get-caller-identity --query Account --output text

  build:
    commands:
      - echo "Building TypeScript for Node.js 24"
      - npm run build
      - echo "SAM build (Node.js 24 runtime)"
      - echo "using bucket $ARTIFACT_BUCKET and region $AWS_DEFAULT_REGION"
      - echo $ARTIFACT_BUCKET
      - sam build --debug --use-container
      - echo "Packaging to $ARTIFACT_BUCKET"
      - sam package \
        --s3-bucket "$ARTIFACT_BUCKET" \
        --output-template-file packaged.yaml \
        --s3-prefix "sam-artifacts/${CODEBUILD_BUILD_NUMBER}/"

  post_build:
    commands:
      - echo "Deploying stack $STACK_NAME"
      - |
        sam deploy \
          --template-file packaged.yaml \
          --stack-name "$STACK_NAME" \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
          --region "$AWS_DEFAULT_REGION" \
          --no-fail-on-empty-changeset \
          --no-confirm-changeset \
          ${PARAM_OVERRIDES:+--parameter-overrides "$PARAM_OVERRIDES"}
        echo "Deployment complete. Stack: $STACK_NAME"

artifacts:
  files:
    - packaged.yaml
    - template.yaml
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*
    - "!(node_modules)/**/*.js"
    - ~/.aws-sam
