version: 0.2

env:
  variables:
    # Required: S3 bucket in pipeline account for SAM packaging artifacts
    ARTIFACT_BUCKET: "your-pipeline-account-artifacts-bucket"
    # Required: CloudFormation stack name to deploy
    STACK_NAME: "your-sam-stack"
    # Required for cross-account: ARN of role in target account
    TARGET_ROLE_ARN: "arn:aws:iam::TARGET_ACCOUNT_ID:role/CrossAccountPipelineRole"
    # Deployment region (target account region)
    AWS_REGION: "ap-south-1"
    # Optional: Parameter overrides for sam deploy
    PARAM_OVERRIDES: ""

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing Node.js 24 + build tools"
      - npm ci --frozen-lockfile
      - npm install -g aws-sam-cli aws-cfn-lint
      - sam --version
      - npm --version
      - node --version

  pre_build:
    commands:
      - echo "Preparing cross-account environment"
      - echo "Pipeline region: $AWS_DEFAULT_REGION"
      - echo "Target region: $AWS_REGION"

      # Assume role in target account for deployment
      # In pre_build phase, replace the assume-role command with:
      - |
        echo "Assuming target role $TARGET_ROLE_ARN with ExternalId $EXTERNAL_ID"
        CREDS=$(aws sts assume-role \
        --role-arn "$TARGET_ROLE_ARN" \
        --role-session-name "codebuild-${CODEBUILD_BUILD_NUMBER}" \
        --external-id "$EXTERNAL_ID" \
        --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
        --output text)

  build:
    commands:
      - echo "Building TypeScript for Node.js 24"
      - npm run build

      - echo "SAM build (Node.js 24 runtime)"
      - sam build --debug --use-container

      - echo "Validating template"
      - cfn-lint template.yaml
      - sam validate --template template.yaml

      - echo "Packaging to $ARTIFACT_BUCKET"
      - sam package \
        --s3-bucket "$ARTIFACT_BUCKET" \
        --output-template-file packaged.yaml \
        --s3-prefix "sam-artifacts/${CODEBUILD_BUILD_NUMBER}/"

  post_build:
    commands:
      - echo "Deploying stack $STACK_NAME"
      - |
        sam deploy \
          --template-file packaged.yaml \
          --stack-name "$STACK_NAME" \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
          --region "$AWS_DEFAULT_REGION" \
          --no-fail-on-empty-changeset \
          --no-confirm-changeset \
          ${PARAM_OVERRIDES:+--parameter-overrides "$PARAM_OVERRIDES"}
          
        echo "Deployment complete. Stack: $STACK_NAME"

artifacts:
  files:
    - packaged.yaml
    - template.yaml
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*
    - "!(node_modules)/**/*.js"
    - ~/.aws-sam
